// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandaBot.Core.Data;

#nullable disable

namespace PandaBot.Migrations
{
    [DbContext(typeof(PandaBotContext))]
    partial class PandaBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PandaBot.Core.Models.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastNewsCheck")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("NewsChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedCraftingRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CraftTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputItemCachedId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Station")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OutputItemCachedId");

                    b.HasIndex("Profession");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("CachedCraftingRecipes");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enchantable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalIconPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxStackSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorValueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Rarity");

                    b.HasIndex("Type");

                    b.ToTable("CachedItems");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedMob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBoss")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsElite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MobId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("CachedMobs");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedRecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachedCraftingRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CachedCraftingRecipeId");

                    b.HasIndex("ItemId");

                    b.ToTable("CachedRecipeIngredients");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CachedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("VendorId")
                        .IsUnique();

                    b.ToTable("CachedVendors");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.MobItemDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachedItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachedMobId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DropRate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CachedItemId");

                    b.HasIndex("CachedMobId", "CachedItemId")
                        .IsUnique();

                    b.ToTable("MobItemDrops");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.MobRecipeDrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachedCraftingRecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CachedMobId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("DropRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CachedCraftingRecipeId");

                    b.HasIndex("CachedMobId", "CachedCraftingRecipeId")
                        .IsUnique();

                    b.ToTable("MobRecipeDrops");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedCraftingRecipe", b =>
                {
                    b.HasOne("PandaBot.Models.AshesOfCreation.CachedItem", "OutputItem")
                        .WithMany()
                        .HasForeignKey("OutputItemCachedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OutputItem");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedRecipeIngredient", b =>
                {
                    b.HasOne("PandaBot.Models.AshesOfCreation.CachedCraftingRecipe", "CachedCraftingRecipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("CachedCraftingRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CachedCraftingRecipe");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.MobItemDrop", b =>
                {
                    b.HasOne("PandaBot.Models.AshesOfCreation.CachedItem", "CachedItem")
                        .WithMany("MobDrops")
                        .HasForeignKey("CachedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PandaBot.Models.AshesOfCreation.CachedMob", "CachedMob")
                        .WithMany("ItemDrops")
                        .HasForeignKey("CachedMobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CachedItem");

                    b.Navigation("CachedMob");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.MobRecipeDrop", b =>
                {
                    b.HasOne("PandaBot.Models.AshesOfCreation.CachedCraftingRecipe", "CachedCraftingRecipe")
                        .WithMany("MobDrops")
                        .HasForeignKey("CachedCraftingRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PandaBot.Models.AshesOfCreation.CachedMob", "CachedMob")
                        .WithMany("RecipeDrops")
                        .HasForeignKey("CachedMobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CachedCraftingRecipe");

                    b.Navigation("CachedMob");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedCraftingRecipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("MobDrops");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedItem", b =>
                {
                    b.Navigation("MobDrops");
                });

            modelBuilder.Entity("PandaBot.Models.AshesOfCreation.CachedMob", b =>
                {
                    b.Navigation("ItemDrops");

                    b.Navigation("RecipeDrops");
                });
#pragma warning restore 612, 618
        }
    }
}
