name: .NET CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/dotnet.yml'
      - '!**/*.md'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'tools/**'
      - '.github/workflows/dotnet.yml'
      - '!**/*.md'

env:
  DOTNET_VERSION: '10.0.x'
  PROJECT_PATH: 'src/PandaBot/PandaBot.csproj'

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build VersionManager
        run: dotnet build tools/VersionManager/VersionManager.csproj --configuration Release

      - name: Check commits since last version
        run: dotnet artifacts/bin/VersionManager/release/VersionManager.dll check-commits || true

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }} --verbosity diagnostic

      - name: Build
        env:
          UEX__BearerToken: ${{ secrets.UEX_BEARER_TOKEN }}
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: PandaBot-publish
          path: publish/
